### ISSUE TITLE
Errors when running the test script (at least) on the Windows platform

### ISSUE THREAD

**Issue by doberkofler** [flow-typed/flow-typed#1373]
When running `jest && npm run lint` on the Windows platform a few tests fail. Some time ago I files a PR that corrected all of these failed unit tests but now they seem to be back and it seems to be as if the Windows platform would not be part of the CI.

```
> jest && npm run lint

 FAIL  src\lib\npm\__tests__\npmLibDefs-test.js
  ● npmLibDefs › getInstalledNpmLibDefs › finds unscoped libdefs

    expect(received).toBe(expected)

    Expected value to be (using ===):
      2
    Received:
      0

      at _callee7$ (src/lib/npm/__tests__/npmLibDefs-test.js:313:45)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:155:20)
      at node_modules/regenerator-runtime/runtime.js:165:13
          at <anonymous>

  ● npmLibDefs › getInstalledNpmLibDefs › finds scoped libdefs

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at _callee8$ (src/lib/npm/__tests__/npmLibDefs-test.js:349:45)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:155:20)
      at node_modules/regenerator-runtime/runtime.js:165:13
          at <anonymous>

  ● npmLibDefs › getInstalledNpmLibDefs › finds libDef with fully-bounded semver range

    expect(received).toBe(expected)

    Expected value to be (using ===):
      2
    Received:
      0

      at _callee9$ (src/lib/npm/__tests__/npmLibDefs-test.js:385:45)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:155:20)
      at node_modules/regenerator-runtime/runtime.js:165:13
          at <anonymous>

 PASS  src\lib\__tests__\libDefs-test.js
 PASS  src\commands\__tests__\search-test.js
 PASS  src\lib\__tests__\flowVersion-test.js
 PASS  src\lib\__tests__\cacheRepoUtils-test.js
 PASS  src\lib\__tests__\semver-test.js
 PASS  src\lib\__tests__\codeSign-test.js
 PASS  src\commands\__tests__\install-test.js (7.38s)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       3 failed, 91 passed, 94 total
Snapshots:   0 total
Time:        9.81s, estimated 11s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-typed@2.2.0 test-quick: `jest && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-typed@2.2.0 test-quick script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\doberkofler.LBITS\AppData\Roaming\npm-cache\_logs\2017-10-17T15_25_23_973Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-typed@2.2.0 test: `npm run clean && npm run build && npm run test-quick`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-typed@2.2.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\doberkofler.LBITS\AppData\Roaming\npm-cache\_logs\2017-10-17T15_25_24_225Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flow-typed@2.2.0 prepublish: `mkdirp dist && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flow-typed@2.2.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\doberkofler.LBITS\AppData\Roaming\npm-cache\_logs\2017-10-17T15_25_24_486Z-debug.log
```

**Comment by GAntoine** [comment]
This also happens on mac when trying to run the test suite after using `eslint --fix` or `prettier --write`. It seems whatever gets written out makes a few of the specs unhappy.

**Comment by doberkofler** [comment]
I understand but do actually not explicitly invoke `eslint --fix` or `prettier --write` but rather the build process of flow-typed does so automatically. I would suggest to rather not automatically fix any styling.
