### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Ridermansb** [flow-typed/flow-typed#2529]
**Command executed**: ` yarn add flow-typed --verbose -D`

**Error** `Error: Received malformed response from registry for undefined. The registry may be down.`

**Environment**

```
▶ yarn -v
1.7.0
▶ npm -v
6.2.0
▶ node -v
v10.7.0
```

**Output** ..

```
▶ yarn add flow-typed --verbose -D
yarn add v1.7.0
verbose 0.47 Checking for configuration file "[OMITTED]/web/.npmrc".
verbose 0.471 Checking for configuration file "/Users/ridermansb/.npmrc".
verbose 0.471 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.471 Checking for configuration file "[OMITTED]/web/.npmrc".
verbose 0.472 Checking for configuration file "[OMITTED]/.npmrc".
verbose 0.472 Checking for configuration file "/Users/ridermansb/Projects/.npmrc".
verbose 0.472 Checking for configuration file "/Users/ridermansb/.npmrc".
verbose 0.472 Checking for configuration file "/Users/.npmrc".
verbose 0.473 Checking for configuration file "[OMITTED]/web/.yarnrc".
verbose 0.473 Checking for configuration file "/Users/ridermansb/.yarnrc".
verbose 0.474 Found configuration file "/Users/ridermansb/.yarnrc".
verbose 0.474 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.474 Checking for configuration file "[OMITTED]/web/.yarnrc".
verbose 0.474 Checking for configuration file "[OMITTED]/.yarnrc".
verbose 0.475 Checking for configuration file "/Users/ridermansb/Projects/.yarnrc".
verbose 0.475 Checking for configuration file "/Users/ridermansb/.yarnrc".
verbose 0.475 Found configuration file "/Users/ridermansb/.yarnrc".
verbose 0.475 Checking for configuration file "/Users/.yarnrc".
verbose 0.479 current time: 2018-07-24T00:43:46.831Z
[1/4] 🔍  Resolving packages...
verbose 0.993 Performing "GET" request to "https://registry.yarnpkg.com/flow-typed".
(node:64129) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
verbose 3.809 Request "https://registry.yarnpkg.com/flow-typed" finished with status code 200.
verbose 3.816 Performing "GET" request to "https://registry.yarnpkg.com/@octokit%2frest".
verbose 3.817 Performing "GET" request to "https://registry.yarnpkg.com/colors".
verbose 3.82 Performing "GET" request to "https://registry.yarnpkg.com/fs-extra".
verbose 3.821 Performing "GET" request to "https://registry.yarnpkg.com/got".
verbose 3.824 Performing "GET" request to "https://registry.yarnpkg.com/md5".
verbose 3.828 Performing "GET" request to "https://registry.yarnpkg.com/table".
verbose 3.829 Performing "GET" request to "https://registry.yarnpkg.com/through".
verbose 3.831 Performing "GET" request to "https://registry.yarnpkg.com/unzipper".
verbose 3.913 Request "https://registry.yarnpkg.com/through" finished with status code 502.
verbose 3.914 Performing "GET" request to "https://registry.yarnpkg.com/which".
verbose 4.168 Request "https://registry.yarnpkg.com/fs-extra" finished with status code 502.
verbose 4.168 Performing "GET" request to "https://registry.yarnpkg.com/yargs".
verbose 4.386 Request "https://registry.yarnpkg.com/colors" finished with status code 200.
verbose 4.867 Request "https://registry.yarnpkg.com/got" finished with status code 200.
verbose 5.136 Request "https://registry.yarnpkg.com/md5" finished with status code 200.
verbose 5.139 Performing "GET" request to "https://registry.yarnpkg.com/charenc".
verbose 5.14 Performing "GET" request to "https://registry.yarnpkg.com/crypt".
verbose 5.142 Performing "GET" request to "https://registry.yarnpkg.com/is-buffer".
verbose 5.613 Request "https://registry.yarnpkg.com/charenc" finished with status code 200.
verbose 5.784 Request "https://registry.yarnpkg.com/crypt" finished with status code 200.
verbose 5.86 Request "https://registry.yarnpkg.com/yargs" finished with status code 200.
verbose 5.871 Performing "GET" request to "https://registry.yarnpkg.com/cliui".
verbose 5.872 Performing "GET" request to "https://registry.yarnpkg.com/decamelize".
verbose 5.873 Performing "GET" request to "https://registry.yarnpkg.com/lodash.assign".
verbose 5.922 Request "https://registry.yarnpkg.com/table" finished with status code 200.
verbose 5.923 Performing "GET" request to "https://registry.yarnpkg.com/os-locale".
verbose 6.128 Request "https://registry.yarnpkg.com/unzipper" finished with status code 200.
verbose 6.128 Performing "GET" request to "https://registry.yarnpkg.com/which-module".
verbose 6.135 Request "https://registry.yarnpkg.com/lodash.assign" finished with status code 502.
verbose 6.135 Performing "GET" request to "https://registry.yarnpkg.com/window-size".
verbose 6.163 Request "https://registry.yarnpkg.com/window-size" finished with status code 502.
verbose 6.164 Performing "GET" request to "https://registry.yarnpkg.com/y18n".
verbose 6.185 Request "https://registry.yarnpkg.com/y18n" finished with status code 502.
verbose 6.185 Performing "GET" request to "https://registry.yarnpkg.com/yargs-parser".
verbose 6.385 Request "https://registry.yarnpkg.com/which-module" finished with status code 502.
verbose 6.386 Performing "GET" request to "https://registry.yarnpkg.com/big-integer".
verbose 6.586 Request "https://registry.yarnpkg.com/@octokit%2frest" finished with status code 200.
verbose 6.587 Performing "GET" request to "https://registry.yarnpkg.com/binary".
verbose 6.619 Request "https://registry.yarnpkg.com/decamelize" finished with status code 200.
verbose 6.619 Performing "GET" request to "https://registry.yarnpkg.com/bluebird".
verbose 6.741 Request "https://registry.yarnpkg.com/is-buffer" finished with status code 200.
verbose 6.741 Performing "GET" request to "https://registry.yarnpkg.com/buffer-indexof-polyfill".
verbose 6.896 Request "https://registry.yarnpkg.com/os-locale" finished with status code 200.
verbose 6.897 Performing "GET" request to "https://registry.yarnpkg.com/duplexer2".
verbose 7.116 Request "https://registry.yarnpkg.com/duplexer2" finished with status code 200.
verbose 7.116 Performing "GET" request to "https://registry.yarnpkg.com/fstream".
verbose 7.43 Request "https://registry.yarnpkg.com/binary" finished with status code 200.
verbose 7.431 Performing "GET" request to "https://registry.yarnpkg.com/listenercount".
verbose 7.462 Request "https://registry.yarnpkg.com/listenercount" finished with status code 502.
verbose 7.462 Performing "GET" request to "https://registry.yarnpkg.com/readable-stream".
verbose 7.576 Request "https://registry.yarnpkg.com/buffer-indexof-polyfill" finished with status code 200.
verbose 7.576 Performing "GET" request to "https://registry.yarnpkg.com/setimmediate".
verbose 7.939 Request "https://registry.yarnpkg.com/cliui" finished with status code 200.
verbose 7.94 Performing "GET" request to "https://registry.yarnpkg.com/before-after-hook".
verbose 8.076 Request "https://registry.yarnpkg.com/fstream" finished with status code 200.
verbose 8.077 Performing "GET" request to "https://registry.yarnpkg.com/btoa-lite".
verbose 8.337 Request "https://registry.yarnpkg.com/readable-stream" finished with status code 200.
verbose 8.339 Performing "GET" request to "https://registry.yarnpkg.com/http-proxy-agent".
verbose 8.432 Request "https://registry.yarnpkg.com/big-integer" finished with status code 200.
verbose 8.433 Performing "GET" request to "https://registry.yarnpkg.com/https-proxy-agent".
verbose 8.445 Request "https://registry.yarnpkg.com/btoa-lite" finished with status code 200.
verbose 8.445 Performing "GET" request to "https://registry.yarnpkg.com/node-fetch".
verbose 8.626 Request "https://registry.yarnpkg.com/before-after-hook" finished with status code 200.
verbose 8.627 Performing "GET" request to "https://registry.yarnpkg.com/url-template".
verbose 8.799 Request "https://registry.yarnpkg.com/setimmediate" finished with status code 200.
verbose 8.8 Performing "GET" request to "https://registry.yarnpkg.com/chainsaw".
verbose 9.136 Request "https://registry.yarnpkg.com/url-template" finished with status code 200.
verbose 9.136 Performing "GET" request to "https://registry.yarnpkg.com/buffers".
verbose 9.196 Request "https://registry.yarnpkg.com/node-fetch" finished with status code 200.
verbose 9.196 Performing "GET" request to "https://registry.yarnpkg.com/inherits".
verbose 9.23 Request "https://registry.yarnpkg.com/http-proxy-agent" finished with status code 200.
verbose 9.23 Performing "GET" request to "https://registry.yarnpkg.com/mkdirp".
verbose 9.356 Request "https://registry.yarnpkg.com/chainsaw" finished with status code 200.
verbose 9.356 Performing "GET" request to "https://registry.yarnpkg.com/rimraf".
verbose 9.582 Request "https://registry.yarnpkg.com/bluebird" finished with status code 200.
verbose 9.582 Performing "GET" request to "https://registry.yarnpkg.com/buffer-shims".
verbose 9.792 Request "https://registry.yarnpkg.com/buffers" finished with status code 200.
verbose 9.792 Performing "GET" request to "https://registry.yarnpkg.com/process-nextick-args".
verbose 10 Request "https://registry.yarnpkg.com/buffer-shims" finished with status code 200.
verbose 10.001 Performing "GET" request to "https://registry.yarnpkg.com/agent-base".
verbose 10.093 Request "https://registry.yarnpkg.com/https-proxy-agent" finished with status code 200.
verbose 10.094 Performing "GET" request to "https://registry.yarnpkg.com/debug".
verbose 10.262 Request "https://registry.yarnpkg.com/process-nextick-args" finished with status code 200.
verbose 10.263 Performing "GET" request to "https://registry.yarnpkg.com/traverse".
verbose 10.431 Request "https://registry.yarnpkg.com/agent-base" finished with status code 200.
verbose 10.433 Performing "GET" request to "https://registry.yarnpkg.com/es6-promisify".
verbose 10.685 Request "https://registry.yarnpkg.com/traverse" finished with status code 200.
verbose 10.726 Request "https://registry.yarnpkg.com/rimraf" finished with status code 200.
verbose 11.09 Request "https://registry.yarnpkg.com/es6-promisify" finished with status code 200.
verbose 11.092 Performing "GET" request to "https://registry.yarnpkg.com/es6-promise".
verbose 11.101 Request "https://registry.yarnpkg.com/inherits" finished with status code 200.
verbose 11.174 Request "https://registry.yarnpkg.com/mkdirp" finished with status code 200.
verbose 11.618 Request "https://registry.yarnpkg.com/debug" finished with status code 200.
verbose 11.639 Request "https://registry.yarnpkg.com/es6-promise" finished with status code 200.
verbose 11.639 Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
verbose 36.93 Performing "GET" request to "https://registry.yarnpkg.com/which".
verbose 36.932 Performing "GET" request to "https://registry.yarnpkg.com/yargs-parser".
verbose 36.959 Request "https://registry.yarnpkg.com/which" finished with status code 502.
verbose 37.254 Request "https://registry.yarnpkg.com/yargs-parser" finished with status code 200.
verbose 37.257 Performing "GET" request to "https://registry.yarnpkg.com/camelcase".
verbose 38.965 Request "https://registry.yarnpkg.com/camelcase" finished with status code 200.
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:23451:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.7.0/libexec/lib/cli.js:52217:19)
```

**Comment by AndrewSouthpaw** [comment]
Try back later and let us know if it's still happening?
