### ISSUE TITLE
Set up AppVeyor

### ISSUE THREAD

**Issue by gabelevi** [flow-typed/flow-typed#253]
Need to make sure that the cli doesn't break on Windows.

**Comment by marudor** [comment]
Would do that, need flowtype organisation access though.

**Comment by szarouski** [comment]
Hi, Current version is not working on windows:

```
C:\dev\bugsnag-sourcemaps>flow-typed install -f 0.30 debug@2.2.0
C:\Users\szarouski\AppData\Roaming\npm\node_modules\flow-typed\dist\commands\run
Tests.js:45
      throw new Error("Unsupported os.type()! " + _node.os.type());
      ^

Error: Unsupported os.type()! Windows_NT
    at C:\Users\szarouski\AppData\Roaming\npm\node_modules\flow-typed\dist\comma
nds\runTests.js:45:13
    at Object.<anonymous> (C:\Users\szarouski\AppData\Roaming\npm\node_modules\f
low-typed\dist\commands\runTests.js:47:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\szarouski\AppData\Roaming\npm\node_modules\f
low-typed\dist\cli.js:22:17)
```

Should I create a new issue or this thread is good enough?
Thank you.

**Comment by jeffmo** [comment]
@szarouski: I pushed a fix for this yesterday, but haven't published it yet: https://github.com/flowtype/flow-typed/commit/567032eb631e873d457bf5ffe51b99c02a44e9b6

Will do this very soon: I'm trying to get a few more PRs merged before publishing the next beta release.
