### ISSUE TITLE
Uncaught Error: fuzzaldrin-plus_v0.6.0

### ISSUE THREAD

**Issue by famoraes** [flow-typed/flow-typed#2636]
Heyo all,
While trying to install deps `flow-typed install`, I'm facing this issue:
```
UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `fuzzaldrin-plus_v0.6.0.js`.
    at validationError (/Users/famoraes/.config/yarn/global/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /Users/famoraes/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/Users/famoraes/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:95:23)
    at tryCatch (/Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Users/famoraes/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:165:13
```

Which is weird because I don't have this library installed (at any level) in my project. I've ran `yarn list` and couldn't found it.  Am I missing something?

Thanks!

**Comment by kadikraman** [comment]
Had the same issue. Happened even on a fresh project. Tried a few things and it started working after I did all of the following (not sure which of this fixed it, but maybe it'll help someone 😄)
```
nvm use 8
npm i -g flow-typed@v2.4.0
yarn cache clean
```

**Comment by samufort** [comment]
It helped someone !
Cleaning the cache did nothing, upgrading flow-typed fixed the error

**Comment by fossage** [comment]
I was having this same issue when I was using node 8.11.1.  Once I switched to 8.11.3, it worked just fine  ¯\_(ツ)_/¯
