### ISSUE TITLE
UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0/CONTRIBUTING.md: Unexpected file name.

### ISSUE THREAD

**Issue by DanFlor** [flow-typed/flow-typed#2882]
The addition of the fuzzaldrin definition is breaking my flow-typed install.

• Found 142 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: fuzzaldrin-plus_v0.6.0/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `fuzzaldrin-plus_v0.6.0.js`.
    at validationError (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:112:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:94:23)
    at tryCatch (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Users/obidan/Projects/BackpackEMR/igniteremotecare/backpackEMR/node_modules/regenerator-runtime/runtime.js:165:13

**Comment by DanFlor** [comment]
I have tried multiple versions of flow-typed, and all of them bark about CONTRIBUTING.md in fuzzaldrin.  Going to put in a PR to have it removed.

**Comment by DanFlor** [comment]
How do I submit a PR? I can't push a branch.  How do I get access to the project?  I need this fixed ASAP.

**Comment by pascalduez** [comment]
@DanFlor https://help.github.com/articles/creating-a-pull-request ;)

**Comment by DanFlor** [comment]
Pull request #2891 pending.

**Comment by villesau** [comment]
@DanFlor is this still a problem? Looks like you closed the PR. Maybe you just had an old version of flow-typed? :)

**Comment by Soreine** [comment]
@DanFlor  Upgrading flow-typed worked for me as stated here
https://github.com/flow-typed/flow-typed/pull/2499#issuecomment-411451445
