### ISSUE TITLE
Error: Cannot find module 'ajv/lib/compile/equal'

### ISSUE THREAD

**Issue by bluepnume** [flow-typed/flow-typed#2985]
```
> rm -rf flow-typed && flow-typed install

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/db/paypal-checkout/node_modules/flow-typed/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/db/paypal-checkout/node_modules/flow-typed/node_modules/table/dist/makeConfig.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

Looks like this change broke flow-typed: https://github.com/epoberezkin/ajv/commit/f9fcc504a4aaee3653af0f61c7681e2e80557f67

**Comment by micheletedeschi** [comment]
I've resolved specify in package.json the previous version of ajv: ajv@6.5.0

**Comment by sogehige** [comment]
ajv@6.6.1 fixed issue
