### ISSUE TITLE
`flow-typed install` leads to an error because an extra space is being appended to a path

### ISSUE THREAD

**Issue by kaiyoma** [flow-typed/flow-typed#3079]
If I run `flow-typed install`, I get a bunch of output and then this error:

```
UNCAUGHT ERROR: Error: Unable to find `node_modules/@babel/runtime /` install directory! Did you forget to run `npm install` before running `flow-typed install`?
    at resolvePkgDirPath$ (...\node_modules\flow-typed\dist\lib\stubUtils.js:93:17)
    at tryCatch (...\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (...\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (...\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (...\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (...\node_modules\regenerator-runtime\runtime.js:155:20)
    at ...\node_modules\regenerator-runtime\runtime.js:165:13
```

For some reason, the last token of the path ("runtime") has a space appended to it, which leads to this error, because of course that directory doesn't exist. The correct directory name does exist:

```
$ ls "node_modules/@babel/runtime/"
helpers/  LICENSE  package.json  README.md  regenerator/
```

Here's the full output:

```
$ flow-typed install
• Found 193 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 36 libDefs...
  • bignumber.js_v7.x.x.js
    └> .\flow-typed\npm\bignumber.js_v7.x.x.js
bignumber.js
...\flow-typed\npm
  • loglevel_v1.x.x.js
    └> .\flow-typed\npm\loglevel_v1.x.x.js
loglevel
...\flow-typed\npm
  • axios_v0.18.x.js
    └> .\flow-typed\npm\axios_v0.18.x.js
axios
...\flow-typed\npm
  • polyfill_v7.x.x.js
    └> .\flow-typed\npm\@babel\polyfill_v7.x.x.js
polyfill
...\flow-typed\npm\@babel
  • react-ace_v6.x.x.js
    └> .\flow-typed\npm\react-ace_v6.x.x.js
react-ace
...\flow-typed\npm
  • lodash_v4.x.x.js
    └> .\flow-typed\npm\lodash_v4.x.x.js
lodash
...\flow-typed\npm
  • redux_v3.x.x.js
    └> .\flow-typed\npm\redux_v3.x.x.js
redux
...\flow-typed\npm
  • url-parse_v1.3.x.js
    └> .\flow-typed\npm\url-parse_v1.3.x.js
url-parse
...\flow-typed\npm
  • react-redux_v5.x.x.js
    └> .\flow-typed\npm\react-redux_v5.x.x.js
react-redux
...\flow-typed\npm
  • pluralize_v7.x.x.js
    └> .\flow-typed\npm\pluralize_v7.x.x.js
pluralize
...\flow-typed\npm
  • react_v4.x.x.js
    └> .\flow-typed\npm\@storybook\react_v4.x.x.js
react
...\flow-typed\npm\@storybook
  • simple-query-string_v1.x.x.js
    └> .\flow-typed\npm\simple-query-string_v1.x.x.js
simple-query-string
...\flow-typed\npm
  • react-copy-to-clipboard_v5.x.x.js
    └> .\flow-typed\npm\react-copy-to-clipboard_v5.x.x.js
react-copy-to-clipboard
...\flow-typed\npm
  • classnames_v2.x.x.js
    └> .\flow-typed\npm\classnames_v2.x.x.js
classnames
...\flow-typed\npm
  • react-bootstrap_v0.32.x.js
    └> .\flow-typed\npm\react-bootstrap_v0.32.x.js
react-bootstrap
...\flow-typed\npm
  • re-reselect_v2.x.x.js
    └> .\flow-typed\npm\re-reselect_v2.x.x.js
re-reselect
...\flow-typed\npm
  • reselect_v3.x.x.js
    └> .\flow-typed\npm\reselect_v3.x.x.js
reselect
...\flow-typed\npm
  • flow-bin_v0.x.x.js
    └> .\flow-typed\npm\flow-bin_v0.x.x.js
flow-bin
...\flow-typed\npm
  • semver_v5.1.x.js
    └> .\flow-typed\npm\semver_v5.1.x.js
semver
...\flow-typed\npm
  • prop-types_v15.x.x.js
    └> .\flow-typed\npm\prop-types_v15.x.x.js
prop-types
...\flow-typed\npm
  • selenium-webdriver_v3.x.x.js
    └> .\flow-typed\npm\selenium-webdriver_v3.x.x.js
selenium-webdriver
...\flow-typed\npm
  • uuid_v3.x.x.js
    └> .\flow-typed\npm\uuid_v3.x.x.js
uuid
...\flow-typed\npm
  • redux-mock-store_v1.2.x.js
    └> .\flow-typed\npm\redux-mock-store_v1.2.x.js
redux-mock-store
...\flow-typed\npm
  • mocha_v5.x.x.js
    └> .\flow-typed\npm\mocha_v5.x.x.js
mocha
...\flow-typed\npm
  • register_v7.x.x.js
    └> .\flow-typed\npm\@babel\register_v7.x.x.js
register
...\flow-typed\npm\@babel
  • enzyme_v3.x.x.js
    └> .\flow-typed\npm\enzyme_v3.x.x.js
enzyme
...\flow-typed\npm
  • react-hot-loader_v4.x.x.js
    └> .\flow-typed\npm\react-hot-loader_v4.x.x.js
react-hot-loader
...\flow-typed\npm
  • webpack_v4.x.x.js
    └> .\flow-typed\npm\webpack_v4.x.x.js
webpack
...\flow-typed\npm
  • history_v4.x.x.js
    └> .\flow-typed\npm\history_v4.x.x.js
history
...\flow-typed\npm
  • moment_v2.x.x.js
    └> .\flow-typed\npm\moment_v2.x.x.js
moment
...\flow-typed\npm
  • react-test-renderer_v16.x.x.js
    └> .\flow-typed\npm\react-test-renderer_v16.x.x.js
react-test-renderer
...\flow-typed\npm
  • chalk_v2.x.x.js
    └> .\flow-typed\npm\chalk_v2.x.x.js
chalk
...\flow-typed\npm
  • jest_v23.x.x.js
    └> .\flow-typed\npm\jest_v23.x.x.js
jest
...\flow-typed\npm
  • chai_v4.x.x.js
    └> .\flow-typed\npm\chai_v4.x.x.js
chai
...\flow-typed\npm
  • numeral_v2.x.x.js
    └> .\flow-typed\npm\numeral_v2.x.x.js
numeral
...\flow-typed\npm
  • mysql_v2.x.x.js
    └> .\flow-typed\npm\mysql_v2.x.x.js
mysql
...\flow-typed\npm
UNCAUGHT ERROR: Error: Unable to find `node_modules/@babel/runtime /` install directory! Did you forget to run `npm install` before running `flow-typed install`?
    at resolvePkgDirPath$ (...\node_modules\flow-typed\dist\lib\stubUtils.js:93:17)
    at tryCatch (...\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (...\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (...\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (...\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (...\node_modules\regenerator-runtime\runtime.js:155:20)
    at ...\node_modules\regenerator-runtime\runtime.js:165:13
```

**Comment by kaiyoma** [comment]
Never mind. We had a trailing space for the package name in our package.json. Somehow most of our other tools continued to work anyway!
