### ISSUE TITLE
CLI libDefs-test fails in NodeJS 11

### ISSUE THREAD

**Issue by hWorblehat** [flow-typed/flow-typed#3247]
Hi,

On a clean checkout of the repository with NodeJS 11, running `build_and_test_cli.sh` or `yarn install` inside the `cli` folder both fail. In both cases the first failure occurs when running `libDefs-test.js`, producing the following error:

```
 FAIL  src/lib/__tests__/libDefs-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      11 | export function copyDir(srcPath: string, destPath: string): Promise<void> {
      12 |   return new Promise((res, rej) => {
    > 13 |     fsExtra.copy(srcPath, destPath, err => {
         |                                       ^
      14 |       if (err) {
      15 |         rej(err);
      16 |       } else {

      at patch (node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:27:18)
      at Object.<anonymous> (node_modules/fs-extra/lib/fs/index.js:5:12)
      at Object.<anonymous> (node_modules/fs-extra/lib/index.js:6:3)
      at Object.<anonymous> (src/lib/fileUtils.js:13:39)
      at Object.<anonymous> (src/lib/libDefs.js:18:18)
      at Object.<anonymous> (src/lib/__tests__/libDefs-test.js:11:16)
```
 I can get round this by adding `jest.unmock('graceful-fs/fs');` to the beginning of `libDefs-test.js`, but then the fuzzy filter tests in that file fail with the expected and actual result arrays being in different orders.

I feel like I must be missing something here, since this failure is so easy to produce for me, but I can't work it out. I've also tried checkout out the `v2.4.0` tag and get the same result.

I'm running Ubuntu 18.10 with NodeJS 11.12.0. I have checked previous major versions of NodeJS, and only 11 exhibits this problem. I'll switch down to 10 for the time being.

**Comment by holograph** [comment]
Similar issue on Mac OS with Node.js 12.4.0, albeit with a slightly different error message:

```
 FAIL  src/lib/__tests__/libDefs-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'prototype' of undefined

      1 | // @flow
      2 |
    > 3 | import fsExtra from 'fs-extra';
        | ^
      4 |
      5 | import mkdirpCb from 'mkdirp';
      6 |

      at patch (node_modules/graceful-fs/graceful-fs.js:166:54)
      at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:27:18)
      at Object.<anonymous> (node_modules/fs-extra/lib/fs/index.js:5:12)
      at Object.<anonymous> (node_modules/fs-extra/lib/index.js:6:3)
      at Object.<anonymous> (src/lib/fileUtils.js:3:1)
      at Object.<anonymous> (src/lib/libDefs.js:6:1)
      at Object.<anonymous> (src/lib/__tests__/libDefs-test.js:10:1)
```

**Comment by Brianzchen** [comment]
Tested on node v12.22.7 and we have since dropped support for node 11. Will close but if you find anymore issues feel free to raise
