### ISSUE TITLE
[cli] flow-types search exception

### ISSUE THREAD

**Issue by pascalduez** [flow-typed/flow-typed#3392]
`node -v v10.15.2`  
`flow-typed -v 2.5.2`

```
➜ flow-typed search express 
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
• rebasing flow-typed cache...done.
UNCAUGHT ERROR: Error: Flow versions not disjoint!
    at _callee11$ (/.../node_modules/flow-typed/dist/lib/libDefs.js:612:19)
    at tryCatch (/.../node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/.../node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/.../node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/.../node_modules/flow-typed/dist/lib/libDefs.js:38:103)
    at _next (/.../node_modules/flow-typed/dist/lib/libDefs.js:40:194)

```

**Comment by sohilpandya** [comment]
I'll add the error I'm getting down below as well, similar but points to `code-frame`

looking into this and will update if we have a solution
```
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
• Found 62 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: npm/@babel/code-frame_v7.x.x: Flow versions not disjoint!
    at validationError (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at extractLibDefsFromNpmPkgDir$ (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:128:51)
    at tryCatch (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Users/sohilpandya/Documents/github/microservice-products-v2/node_modules/regenerator-runtime/runtime.js:165:13
```

**Comment by uatec** [comment]
This PR (https://github.com/flow-typed/flow-typed/pull/3390/files#diff-0b7bdbb854f70089e1ba465a4894f81e) has overlapping flow version ranges, which is causing a validation error.

**Comment by uatec** [comment]
Related To: https://github.com/flow-typed/flow-typed/issues/3393
