### ISSUE TITLE
"Invalid Version: undefined" semver on version 3.x flow-typed

### ISSUE THREAD

**Issue by ghtjiann4321** [flow-typed/flow-typed#3809]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
after running yarn flow-typed install
```
UNCAUGHT ERROR: TypeError: Invalid Version: undefined
    at new SemVer (/path/project/node_modules/flow-typed/node_modules/semver/classes/semver.js:22:13)
error Command failed with exit code 1.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Install Fresh CRA
- install flow-bin flow-typed
- run yarn flow init
- run yarn flow-typed install

**What is the expected behavior?**
- should generate the flow-typed directory

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.

kubuntu: 19.04
node: 10.18.1
flow-typed: 3.1.0
flow-bin: 0.122.0

**Comment by dstaley** [comment]
This is almost certainly due to [this bug](https://github.com/npm/node-semver/issues/323).

**Comment by bradvogel** [comment]
Is there a workaround?

**Comment by pzrq** [comment]
> Is there a workaround?

So far I've seen downgrading flow-typed (if one can) to v2.6.2 or manually pinning semver to a known good version in `yarn.lock` such as:

```
semver@^7.1.3:
  version "7.1.3"
  resolved "https://npm.shootsta.com/semver/-/semver-7.1.3.tgz#e4345ce73071c53f336445cfc19efb1c311df2a6"
  integrity sha512-ekM0zfiA9SCBlsKa2X1hxyxiI4L3B6EbVJkkdgQXnSEEaHlGdvyodMruTiulSRWMMB4NeIuYNMC9rTKTz97GxA==
```

**Comment by GAntoine** [comment]
I won't get around to getting. this fixed until this weekend, so if someone is willing to open a PR that fixes the issue in the code, that would be great! If not, I'll try my hand at it, or end up pinning `semver` to a lower version.

**Comment by randallb** [comment]
You can also pin using yarn resolutions in package.json.

https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by xthule** [comment]
It looks like the "bug" from semver isn't going to be fixed.

**Comment by linonetwo** [comment]
But I actully don't have a version in form of `v0.0.x` @xthule

**Comment by xthule** [comment]
> But I actully don't have a version in form of `v0.0.x` @xthule

It doesn't matter; the error occurs because of the flow-typed cache that does contain versions in the for of `v0.0.x`.

**Comment by kylepeeler** [comment]
Also running into this and is a blocker for me upgrading from v2 -> v3 of flow-typed

**Comment by gwing33** [comment]
Is there an alternative workaround for those who don't use yarn?

**Comment by michaelrodov** [comment]
> You can also pin using yarn resolutions in package.json.
> 
> https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it
> 
> ```
> "resolutions": {
>     "flow-typed/semver": "7.1.3"
>   }
> ```

how do you run "flow-typed install" it still gives me the error

**Comment by linonetwo** [comment]
Seems npm don't have a pin command like yarn...

**Comment by pascalduez** [comment]
Should be fixed as of [`v3.2.0`](https://github.com/flow-typed/flow-typed/releases/tag/v3.2.0)

Please comment if not.

**Comment by dstaley** [comment]
I'm still seeing the same error with `v3.2.0`

```
+ flow-typed@3.2.0
added 111 packages from 58 contributors and audited 2085 packages in 13.546s
61 packages are looking for funding
  run `npm fund` for details
found 13256 vulnerabilities (13255 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
• Found 69 dependencies in package.json to install libdefs for. Searching...
• flow-typed cache not found, fetching from GitHub...
UNCAUGHT ERROR: TypeError: Invalid Version: undefined
    at new SemVer (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/classes/semver.js:22:13)
    at outside (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/ranges/outside.js:12:13)
    at Object.gtr (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/ranges/gtr.js:3:42)
    at pkgVersionMatch (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:262:42)
    at defs.filter.def (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:281:82)
    at Array.filter (<anonymous>)
    at filterLibDefs (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:275:15)
    at findNpmLibDef (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:329:27)
```

**Comment by xthule** [comment]
> I'm still seeing the same error with `v3.2.0`
> 
> ```
> + flow-typed@3.2.0
> added 111 packages from 58 contributors and audited 2085 packages in 13.546s
> 61 packages are looking for funding
>   run `npm fund` for details
> found 13256 vulnerabilities (13255 low, 1 moderate)
>   run `npm audit fix` to fix them, or `npm audit` for details
> • Found 69 dependencies in package.json to install libdefs for. Searching...
> • flow-typed cache not found, fetching from GitHub...
> UNCAUGHT ERROR: TypeError: Invalid Version: undefined
>     at new SemVer (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/classes/semver.js:22:13)
>     at outside (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/ranges/outside.js:12:13)
>     at Object.gtr (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/node_modules/semver/ranges/gtr.js:3:42)
>     at pkgVersionMatch (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:262:42)
>     at defs.filter.def (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:281:82)
>     at Array.filter (<anonymous>)
>     at filterLibDefs (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:275:15)
>     at findNpmLibDef (/home/travis/build/Kinto/kinto-admin/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:329:27)
> ```

What is the output of `npx flow-typed --version`?

**Comment by xthule** [comment]
I missed that `npmLibDefs.js` does the same thing as `install.js`. Sorry.

**Comment by xthule** [comment]
I removed my prior fix in favor of a somewhat better fix with this pull request. I'm still not a huge fan, but the shortcomings of semver require something like this.

I also added tests in the hopes of not missing any other places this might come up.

**Comment by pascalduez** [comment]
Should be fixed as of `v3.2.1`

Please comment if not.

**Comment by RaddishIoW** [comment]
Still happens for me...
`UNCAUGHT ERROR: Error: vundefined is a malformed version string. Expected a version formatted as /^([><]=?)?v([0-9]+).([0-9]+|x).([0-9]+|x)(-.*)?(_([><]=?)v([0-9]+).([0-9]+|x).([0-9]+|x)(-.*)?)?$/
    at stringToVersion (/Users/raddish/Development/Hayl/Hayl-UI/node_modules/flow-typed/dist/lib/semver.js:48:11)
    at determineFlowVersion (/Users/raddish/Development/Hayl/Hayl-UI/node_modules/flow-typed/dist/lib/npm/npmProjectUtils.js:110:40)
    at async findFlowSpecificVer (/Users/raddish/Development/Hayl/Hayl-UI/node_modules/flow-typed/dist/lib/npm/npmProjectUtils.js:117:22)
    at async determineFlowVersion (/Users/raddish/Development/Hayl/Hayl-UI/node_modules/flow-typed/dist/commands/install.js:184:12)
    at async Object.run (/Users/raddish/Development/Hayl/Hayl-UI/node_modules/flow-typed/dist/commands/install.js:110:23)`

**Comment by RaddishIoW** [comment]
Ah... I had flow-bin defined in my package.json file as `"flow-bin": "^0"`.

Changed to `"flow-bin": "^0.134.0"` and it works.

**Comment by jasel-lewis** [comment]
Still seeing this error.

Environment:
Node v14.15.3
npm v6.14.9

Repro:
1. `npx create-electron-app my-app`
2. `npm install eslint --save-dev`
3. `./node_modules/.bin/eslint --init`

Config selections:
- To check syntax, find problems, and enforce code style
- JavaScript modules (import/export)
- React
- Does your project use TypeScript: No
- Where does your code run? Browser
- Use a popular style guide
- Standard: https://github.com/standard/standard
- What format do you want your config file to be in? JavaScript

Results:
```txt
Checking peerDependencies of eslint-config-standard@latest

Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: Invalid Version: undefined
    at new SemVer (D:\Repos.Private\my-app\node_modules\semver\classes\semver.js:19:13)
    at outside (D:\Repos.Private\my-app\node_modules\semver\ranges\outside.js:12:13)
    at Object.ltr (D:\Repos.Private\my-app\node_modules\semver\ranges\ltr.js:3:42)
    at TogglePrompt.message (D:\Repos.Private\my-app\node_modules\eslint\lib\init\config-initializer.js:569:37)
    at Object.exports.resolve (D:\Repos.Private\my-app\node_modules\enquirer\lib\utils.js:43:18)
    at TogglePrompt.resolve (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:373:18)
    at TogglePrompt.element (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:249:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TogglePrompt.message (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:270:19)
    at async TogglePrompt.render (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompts\toggle.js:91:19)
```

**Comment by andrevinsky** [comment]
```txt
> $(npm bin)/flow-typed --version
3.2.1
```

```txt
> $(npm bin)/flow-typed install
• Found 82 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: Invalid npm libdef version! It appears to be a non-continugous range.
    at pkgVersionMatch (<...>maa-client/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:256:11)
    at <...>maa-client/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:281:82
    at Array.filter (<anonymous>)
    at filterLibDefs (<...>maa-client/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:275:15)
    at findNpmLibDef (<...>maa-client/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:329:27)
    at async <...>maa-client/node_modules/flow-typed/dist/commands/install.js:273:20
    at async Promise.all (index 66)
    at async installNpmLibDefs (<...>maa-client/node_modules/flow-typed/dist/commands/install.js:268:3)
    at async Object.run (<...>maa-client/node_modules/flow-typed/dist/commands/install.js:149:27)
```

package.json (excerpt):
```json
{
    "flow-bin": "^0.143.1",
    "flow-typed": "^3.2.1",
    "flow-watch": "^2.0.0",
}
```

**Comment by KailoveQ** [comment]
![image](https://user-images.githubusercontent.com/74295208/110238596-6c53c180-7f7d-11eb-9dc2-46e4a05c4642.png)
I have same question！
