### ISSUE TITLE
install-test is flaky in CI

### ISSUE THREAD

**Issue by jedwards1211** [flow-typed/flow-typed#3965]
Getting this error randomly in some of my PRs ([example](https://github.com/flow-typed/flow-typed/runs/1501427959?check_suite_focus=true)):

```
$ jest && yarn lint
FAIL src/commands/__tests__/install-test.js
  ● install (command) › end-to-end tests › overwrites tweaked libdefs when --overwrite is passed

    expect(received).toBe(expected) // Object.is equality

    Expected: "// flow-typed signature: 7a7fa7619340bfebb825752ae5efb893
    // flow-typed version: 0beab4f35a/foo_v1.x.x/flow_>=v0.38.x·
    "
    Received: ""

      631 | 
      632 |         // Verify that the tweaked libdef file wasn't overwritten
    > 633 |         expect(await (await fs.readFile(libdefFilePath)).toString()).toBe(
          |                                                                      ^
      634 |           libdefFileContent,
      635 |         );
      636 |       });

      at toBe (src/commands/__tests__/install-test.js:633:70)
      at src/commands/__tests__/install-test.js:294:11
      at testProject (src/lib/TEST_UTILS.js:31:3)
      at fakeProjectEnv (src/commands/__tests__/install-test.js:271:14)
```

**Comment by jedwards1211** [comment]
What's with `await (await fs.readFile(libdefFilePath)).toString()`?  `Buffer.toString()` is not async

**Comment by AndrewSouthpaw** [comment]
Is this still an issue for you @jedwards1211?

**Comment by jedwards1211** [comment]
Probably but I don't know yet, my sequelize PR is the first one I've made since reporting this
